# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '就业跟踪' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 就业跟踪

  target '就业跟踪Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '就业跟踪UITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'AFNetworking'
pod 'YYText'
pod 'YYModel'
pod 'SVProgressHUD'
pod 'MJRefresh'
pod 'WMPageController'
pod 'TextFieldEffects'
pod 'SnapKit'
pod 'FSCalendar'
pod 'AwesomeMenu'
end
